platform :ios, '12.0'

use_frameworks!
use_modular_headers!

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  pod 'flutter_inappwebview', '~> 6.1.5'
  pod 'just_audio', '~> 0.9.25'
  pod 'file_picker', '~> 8.1.6'
  pod 'sqflite'
  pod 'path_provider'
  pod 'shared_preferences'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end
